# Generated by Django 4.2 on 2023-06-25 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0005_appointment_delete_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='post',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='category', to=settings.AUTH_USER_MODEL),
        ),
    ]
