# Generated by Django 4.2 on 2023-06-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_category_subscribers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
