# Generated by Django 4.2 on 2023-06-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_delete_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('ARTICLE', 'Статья'), ('NEWS', 'Новости')], default='NEWS', max_length=7, verbose_name='Вид поста'),
        ),
    ]
