# Generated by Django 4.2.4 on 2023-08-17 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pereval_added',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('other_titles', models.CharField(max_length=255)),
                ('connect', models.TextField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('winter_level', models.CharField(choices=[('1a', '1A'), ('1b', '1B'), ('2a', '2A'), ('2b', '2B'), ('3a', '3A'), ('3b', '3B')], default='1a', max_length=2)),
                ('autumn_level', models.CharField(choices=[('1a', '1A'), ('1b', '1B'), ('2a', '2A'), ('2b', '2B'), ('3a', '3A'), ('3b', '3B')], default='1a', max_length=2)),
                ('spring_level', models.CharField(choices=[('1a', '1A'), ('1b', '1B'), ('2a', '2A'), ('2b', '2B'), ('3a', '3A'), ('3b', '3B')], default='1a', max_length=2)),
                ('summer_level', models.CharField(choices=[('1a', '1A'), ('1b', '1B'), ('2a', '2A'), ('2b', '2B'), ('3a', '3A'), ('3b', '3B')], default='1a', max_length=2)),
                ('status', models.CharField(choices=[('new', 'новый'), ('pending', 'модератор взял в работу'), ('accepted', 'модерация прошла успешно'), ('rejected', 'модерация прошла, информация не принята')], default='NE', max_length=8)),
                ('coords', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='pereval.coords')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.IntegerField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('patronimic', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('pereval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pereval.pereval_added')),
            ],
        ),
        migrations.AddField(
            model_name='pereval_added',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.users'),
        ),
    ]
